# Generated by Django 5.0.3 on 2024-03-12 14:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=30)),
                ('customer_contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN', unique=True)),
                ('customer_address', models.TextField()),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('total_cost_without_gst', models.FloatField(default=0.0)),
                ('total_cost_with_offers_and_gst', models.FloatField(default=0.0)),
                ('total_cost_with_gst', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoices.customer')),
                ('invoice_created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('invoice_product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoice_product_quantity', models.PositiveIntegerField()),
                ('invoice_product_cost_per_quantity', models.FloatField(default=0.0)),
                ('invoice_product_total_cost', models.FloatField(default=0.0)),
                ('invoice_product_cost_per_quantity_with_offer', models.FloatField(default=0.0)),
                ('invoice_product_total_cost_with_gst', models.FloatField(default=0.0)),
                ('invoice_product_total_cost_with_offer', models.FloatField(default=0.0)),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_invoice', to='invoices.invoice')),
                ('product_invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_products', to='inventory.product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_number', models.IntegerField()),
                ('transaction_mode', models.CharField(max_length=30)),
                ('transaction_amount', models.FloatField(default=0.0)),
                ('is_successful', models.BooleanField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice_transaction', to='invoices.invoice')),
                ('transaction_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
