# Generated by Django 5.0.3 on 2024-03-12 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('expenses_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenses_total_cost', models.FloatField(default=0.0)),
                ('expenses_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ExpensesDetails',
            fields=[
                ('expenses_details_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('expenses_for', models.TextField()),
                ('expenses_cost', models.FloatField(default=0.0)),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenses_details', to='reports.expenses')),
            ],
        ),
    ]
